<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RemoteAgent.Infrastructure</AssemblyName>
    <RootNamespace>RemoteAgent.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginsContract\PluginsContract.csproj" />
    <ProjectReference Include="..\RemoteAgent.Application\Application.csproj" />
  </ItemGroup>

</Project>
